services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass
    ports:
      - "55432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sample_app
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/db"
      SPRING_DATASOURCE_USERNAME: "admin"
      SPRING_DATASOURCE_PASSWORD: "pass"
    ports:
      - "8080:8080"
    depends_on:
      - db