name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Gradle build
        run: ./gradlew build

      - name: Add VPS to known_hosts
        run: |
          ssh-keyscan -H 185.133.40.247 >> ~/.ssh/known_hosts

      - name: Copy to VPS
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          VPS_USER: ${{ secrets.VPS_USER }}
          VPS_HOST: ${{ secrets.VPS_HOST }}
          VPS_PATH: ${{ secrets.VPS_PATH }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key
          scp -i private_key build/libs/*.jar $VPS_USER@$VPS_HOST:$VPS_PATH
          ssh -i private_key $VPS_USER@$VPS_HOST "docker compose up --build > /dev/null 2>&1 &"
